[Project]
cubic_version = 2026.02.102-release~202602080449~ubuntu24.04.1
first_version = 2026.02.102-release~202602080449~ubuntu24.04.1
create_date = 2026-05-29 11:33
modify_date = 2026-05-29 15:47
directory = /home/prattay/BilepterOSZenshard

[Original]
iso_file_name = debian-live-testing-amd64-standard.iso
iso_directory = /home/prattay/BilepterOSZenshard
iso_volume_id = d-live testing st amd64
iso_release_name = 
iso_disk_name = 

[Custom]
iso_version_number = 2026.05.29
iso_file_name = bilepteros-zenshard.iso
iso_directory = /home/prattay/BilepterOSZenshard
iso_volume_id = BilepterOS-Zenshard
iso_release_name = mint
iso_disk_name = BilepterOS-Zenshard "mint"

[Layout]
casper_directory = install, install/gtk, live
squashfs_directory = live
squashfs_file_name = filesystem.squashfs
manifest_file_name = filesystem.manifest
minimal_remove_file_name = 
standard_remove_file_name = 
size_file_name = filesystem.size
minimal_squashfs_file_name = 
minimal_manifest_file_name = 
minimal_size_file_name = 
standard_squashfs_file_name = 
standard_manifest_file_name = 
standard_size_file_name = 
installer_sources_file_name = 
installer_squashfs_file_name = 
installer_manifest_file_name = 
installer_size_file_name = 
installer_generic_squashfs_file_name = 
installer_generic_manifest_file_name = 
installer_generic_size_file_name = 

[Status]
is_success_analyze = True
is_success_copy = True
is_success_extract = True
iso_template = 789C7D51418E83300CBCF38ADCB8AC0B74DB6EC5437A8D1230D4DA10A32454A555FFBE094B579CF6128DC6CE78C6868BC89F3736D38092DA579E0179BECEDA510B837602806C407753A636DC28233B5F971EAAA3AF1FE858C69E317C2CB07F03350E75FED4CC41D2A07A942D396C02BBF9558CCA050AC416AA1D0D7D9CF7C7C866365219EAAD60BBE5B9EB3C06519DB6E4B54DFDA23A9EB7ACC72656C4E73E83641F3A760D42B2A2B4C10CA235D031C837787AA0D89787F39238E590494686794451DECB328346E445AC19B2D3BD481ABB4685E8586FF937D869B2B166197098CC32325B5E30ACDADF71879521DB31AC8ED0C4C550605026ACBF30EA2754F46ED20576B46EEA5FEDD3D7BEDC1E2F5E03B4F2AD0A5B36E5BF767E3493CF7E00FF17B2C3
iso_checksum = 8a988c5d913ed87fa236fb8eac3d4ba5
iso_checksum_file_name = bilepteros-zenshard.md5

[Options]
update_os_release = True
has_minimal_install = False
boot_configurations = boot/grub/grub.cfg, boot/grub/install.cfg, boot/grub/install_start.cfg, isolinux/install.cfg, isolinux/live.cfg
compression = gzip

